db.user=bank
db.password=bank123
db.url=jdbc:postgresql://postgres:5432/bankdb
db.driver=org.postgresql.Driver

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=none
hibernate.show_sql=false